### ISSUE TITLE
Module v0.3.2 - Error encountered while creating credentials

### ISSUE THREAD

**Issue by oleksiypavlenko** [spotinst/terraform-spotinst-gcp-connect#15]
**What happened**:

This used to work few months ago just fine.
Cannot get module to finish connecting 

```
│ Error: local-exec provisioner error
│ 
│   with module.spotinst.null_resource.account_association,
│   on .terraform/modules/spotinst/main.tf line 87, in resource "null_resource" "account_association":
│   87:     provisioner "local-exec" {
│ 
│ Error running command '.terraform/modules/spotinst/scripts/spot-account set-cloud-credentials act-bb57647a
│ ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAic3BvdC10ZXN0LTYiLAogICJwcml2YXRlX2tleV9pZCI6ICI4M2U2M2ZjNDRmM2RmZTcwMzEyMzljNjUwNTI4MzQzN2M5YWE4ZTVkIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdlFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLY3dnZ1NqQWdFQUFvSUJBUUNKZjhiZklneEZYVHZvXG4wOEpnMEc1aU44SUJTeC9wN1U1UzFUVkNMUWdkNzYxVU9mVGxSUC9RRVFPd0l1WjJ2OVNUdWFkQ0h3bUsvWCt1XG55eEo3dG5pOGxjekRqSm1ZdTVwU3JFR1pVVDJaa1dWYmpqTHBvcnhteU0wOHhEUDRNOThoWTVFZEZlQm8xTVFNXG5SZ1Fob1RuT1oreUExWTZXc0pNakVWS2ltN01lb1dhOUJNazdKWVdUK2dLU3luYzRsS3p3cVA4c2ZMOXgwRm5WXG4rajFoRDdEWFd0UnFqd1l5bGZiS2NwSUZwV2VscnA4bzhieC9hazBXM3RTM082WmRvUy80M0pnVGVocjBWeDV2XG5zTzFCVkNIcWRjclNYelVLVWVOS09JZkZ6UjFobVpIZE1tT25MWVJvcjN4OFNEWCtTbHNPR1ZKRDZXWnl2MTlUXG5paGdvQUJiUkFnTUJBQUVDZ2dFQVBONUgxM2RuSHozS3k2TVNwWEVmckhNcWV4QWFySi9VMEc1NkNUV09KbEozXG4xSlZqaUNzblk2QmtsWkNkbld3R1d1OFEwQUNWWk9ZYm8vRloyVkpKMkpJbjkxbENsWTVYSHNvS3NDaDZzSVRnXG43Y3JoVnZRbm13akJjbWtZNklOdC80WG9NNHYvcitpZ2NSNTlyYldGdFkzajhKU1piclAwTHMzNFd1dTZPNUJwXG5uRkpIVXhBV2oveEtkMFpoNzFTS0Fyckp6YUNWbS9rK0FsaWNtQWZXQllGYWdadmsrQ2hSbXMzU2NJbUI2amMzXG5UdmRlV0FXNGw5Vm9ySUg2QmNxeC95L0h3NVBJNmtUZUhBRHdLVWlXZ1JlZW1LeWJ5VlA5VGpwRjJQWFJOVGU4XG5NSTZsT0lhaUlYTmJZWXNjK0E1YVFMd21UTmdWOCszMmQzVldzUEg5RVFLQmdRQyt6N1RDVVBqSTZmREUvTGY5XG5nUHZFaW9kTFpCc3R5bWdzUm1vVjZET1MybTZVd3VXd01aS3REelUydWZGNXE2a2NEWEFsQ0J3R0lFL21nS3VvXG5kZTR2azBHcUxnLzlsdXdJdlMvT01IckNqVFVDN291em5nNkJEaklZdzhyMnVGQ0FYTldqSjVJN1FoR2d6TGZYXG5jOUVxMVRxYUo5cXNZamlsanVxdEdRQ3VZd0tCZ1FDNGVXY0I5aVVyV2RxeSs5S0NSMmZWdStTcjFtaGpSVGx0XG56WHZuWG8rSzVoZU9jYlZaVzBtNUJ0QWE5MCtyQmVmOXo3enBpTFM4UExWbC9XNDZEUkl5THIxc0o1a1d5Q01LXG45YTQ2Vkc4UVNYZjhjVlYxM1RZbzdnK0JBL1BmVmt2OFNUMmEvSVQ5bmdKTmI1OFF3YVdJNUtJVzhNT091S1AvXG4vbmxpdm5KaU93S0JnRC9xa2JFNXNHeVV1THN6c0dveGg2U0podEtCUVAxd3ZMNkFBODg4emZIV1M0NTNUcnRiXG5qN2Q2emFkOFYrQWEyWFgxSm1peE03bjFudTRta2RuSFR6Y09pOE4yMUpKc3VMb2dyVi9USzN2NkV4VGRWVnlnXG5pRmxBcVJWVW1LdFdpRmpIUUNUNy8yYnNOYjE0ZGVpcytoYndBRVpkTFVuclNQQmtWRVlSaHdIakFvR0FLYUpFXG5yRDJvWCtOVXA0YU1HUmtTaHp0enZaQ1RXS3c3N05zdWRxWngwUkJqQ3FRQklOeW9nOWpVeVBFK0NzUTNlcUlTXG42Y1lQdkZnYlBKeDQ3eU1hRXpkWFN2eVk0WHBqNWtwU2V4bXBRMHpCaHJqeFo3dDRTTDZKd3oxb0llU3hHNHhRXG5HaFdaMGorQ0Y0WDBxV3g2OXExYkk4Qk04bjRialdBYWR6MnlSUmNDZ1lFQXVJS3k1MlZiTmRETVBnYnNKQTV2XG5UL3RFV1IrTUs0WWVnWHZsR2xWSW4vcGV0eXlGNS8zMjhlZkg4aG9NdmJ6MTkvSHYrRmFRMjRPZmFGSVljc0ZKXG5lTXl6VU4zTFV1WHJaU1J5bkxSK2JMMmwxTjBEcHIxRStFSHNPNmxtNjdtc1VqN3Z0aDdBUzhkNzZSQm15eXVVXG5ROWhxYUZVY3RTdEU1RmNyb3lpcXZvQT1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJzcG90LTYwNjA3OTg4MjE4MC1hY3QtYmI1NzY0N2FAc3BvdC10ZXN0LTYuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTA1MTcwOTAxNzc1NzY5MDEyNTA1IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9zcG90LTYwNjA3OTg4MjE4MC1hY3QtYmI1NzY0N2ElNDBzcG90LXRlc3QtNi5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIKfQo=
│ --token=a043d067dd3b1ca42a9c490cc72cfbe748e7f21d374212568ca77407a873d739': exit status 1. Output: Traceback (most recent call last):
│   File "/opt/homebrew/bin/spot-account", line 33, in <module>
│     sys.exit(load_entry_point('spot', 'console_scripts', 'spot-account')())
│              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│   File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
│     return self.main(*args, **kwargs)
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^
│   File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1055, in main
│     rv = self.invoke(ctx)
│          ^^^^^^^^^^^^^^^^
│   File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
│     return _process_result(sub_ctx.command.invoke(sub_ctx))
│                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│   File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
│     return ctx.invoke(self.callback, **ctx.params)
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│   File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 760, in invoke
│     return __callback(*args, **kwargs)
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
│   File "/opt/homebrew/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
│     return f(get_current_context(), *args, **kwargs)
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│   File "/Users/opavlenko/Library/CloudStorage/OneDrive-RokuInc/Code/cti-shared/tf-spot-gcp-connect/.terraform/modules/spotinst/scripts/spot_account.py", line 70, in set_cloud_credentials
│     result = ctx.obj['client2'].set_credentials(gcp_credentials)
│              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│   File "/opt/homebrew/lib/python3.11/site-packages/spotinst_sdk2/clients/setup/__init__.py", line 152, in set_credentials
│     response = self.send_post(
│                ^^^^^^^^^^^^^^^
│   File "/opt/homebrew/lib/python3.11/site-packages/spotinst_sdk2/client.py", line 152, in send_post
│     self.handle_exception("creating {}".format(entity_name), result)
│   File "/opt/homebrew/lib/python3.11/site-packages/spotinst_sdk2/client.py", line 261, in handle_exception
│     raise SpotinstClientException(
│ spotinst_sdk2.client.SpotinstClientException: Error encountered while creating credentials


```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible):**

Use the module v0.3.2

**Anything else we need to know:**

**Environment:**

- Terraform version: 1.2.5
- Module version: 0.3.2
- OS: MacOS
- Kernel:
- Others:

**Comment by oleksiypavlenko** [comment]
Same error occurs in v0.3.4

**Comment by stevenfeltner** [comment]
@oleksiypavlenko Are you running this with terraform cloud or locally on your machine? We have had other users re-install python and correcting the issue.

**Comment by oleksiypavlenko** [comment]
@stevenfeltner I encountered this locally.
Re-installing Python helped, thank you.
